from fastapi import HTTPException

# ── Auth ────────────────────────────────────────────────────────────────────
E_AUTH_REQUIRED = "E_AUTH_REQUIRED"
E_AUTH_INVALID_TOKEN = "E_AUTH_INVALID_TOKEN"
E_AUTH_INVALID_CREDENTIALS = "E_AUTH_INVALID_CREDENTIALS"
E_AUTH_EMAIL_TAKEN = "E_AUTH_EMAIL_TAKEN"
E_AUTH_USERNAME_TAKEN = "E_AUTH_USERNAME_TAKEN"
E_GOOGLE_AUTH_UNAVAILABLE = "E_GOOGLE_AUTH_UNAVAILABLE"

# ── Permission ───────────────────────────────────────────────────────────────
E_FORBIDDEN = "E_FORBIDDEN"
E_BANNED = "E_BANNED"
E_ADMIN_REQUIRED = "E_ADMIN_REQUIRED"
E_MANAGER_REQUIRED = "E_MANAGER_REQUIRED"
E_CHALLENGE_OWNER_REQUIRED = "E_CHALLENGE_OWNER_REQUIRED"

# ── Not Found ────────────────────────────────────────────────────────────────
E_USER_NOT_FOUND = "E_USER_NOT_FOUND"
E_POST_NOT_FOUND = "E_POST_NOT_FOUND"
E_VIDEO_NOT_FOUND = "E_VIDEO_NOT_FOUND"
E_COMMENT_NOT_FOUND = "E_COMMENT_NOT_FOUND"
E_NOTIFICATION_NOT_FOUND = "E_NOTIFICATION_NOT_FOUND"
E_CHALLENGE_NOT_FOUND = "E_CHALLENGE_NOT_FOUND"
E_JOB_NOT_FOUND = "E_JOB_NOT_FOUND"
E_PARTICIPATION_NOT_FOUND = "E_PARTICIPATION_NOT_FOUND"

# ── Video / Upload ───────────────────────────────────────────────────────────
E_VIDEO_DURATION_INVALID = "E_VIDEO_DURATION_INVALID"
E_VIDEO_FORMAT_INVALID = "E_VIDEO_FORMAT_INVALID"
E_VIDEO_TOO_LARGE = "E_VIDEO_TOO_LARGE"
E_AUDIO_DURATION_INVALID = "E_AUDIO_DURATION_INVALID"
E_AUDIO_UPLOAD_FAILED = "E_AUDIO_UPLOAD_FAILED"
E_UPLOAD_URL_FAILED = "E_UPLOAD_URL_FAILED"
E_VIDEO_PROCESS_FAILED = "E_VIDEO_PROCESS_FAILED"
E_QUEUE_FAILED = "E_QUEUE_FAILED"

# ── Image ────────────────────────────────────────────────────────────────────
E_IMAGE_FORMAT_INVALID = "E_IMAGE_FORMAT_INVALID"
E_IMAGE_TOO_LARGE = "E_IMAGE_TOO_LARGE"
E_IMAGE_UPLOAD_FAILED = "E_IMAGE_UPLOAD_FAILED"
E_FILE_TOO_LARGE = "E_FILE_TOO_LARGE"

# ── Comment ──────────────────────────────────────────────────────────────────
E_COMMENT_TOO_SHORT = "E_COMMENT_TOO_SHORT"
E_COMMENT_TOO_LONG = "E_COMMENT_TOO_LONG"
E_COMMENT_DAILY_LIMIT = "E_COMMENT_DAILY_LIMIT"

# ── Challenge ────────────────────────────────────────────────────────────────
E_CHALLENGE_FULL = "E_CHALLENGE_FULL"
E_CHALLENGE_CLOSED = "E_CHALLENGE_CLOSED"
E_CHALLENGE_ENDED = "E_CHALLENGE_ENDED"
E_CHALLENGE_EXPIRED = "E_CHALLENGE_EXPIRED"
E_CHALLENGE_INVALID = "E_CHALLENGE_INVALID"
E_CHALLENGE_NOT_JOINED = "E_CHALLENGE_NOT_JOINED"
E_CHALLENGE_NOT_PARTICIPATING = "E_CHALLENGE_NOT_PARTICIPATING"
E_CHALLENGE_ALREADY_JOINED = "E_CHALLENGE_ALREADY_JOINED"
E_CHALLENGE_ALREADY_COMPLETED = "E_CHALLENGE_ALREADY_COMPLETED"
E_CHALLENGE_TITLE_TAKEN = "E_CHALLENGE_TITLE_TAKEN"
E_CHALLENGE_CREATE_FAILED = "E_CHALLENGE_CREATE_FAILED"

# ── Admin ────────────────────────────────────────────────────────────────────
E_ADMIN_SELF_DELETE = "E_ADMIN_SELF_DELETE"
E_ADMIN_API_KEY_DELETE = "E_ADMIN_API_KEY_DELETE"

# ── Blink (Lightning 지급) ──────────────────────────────────────────────────
E_BLINK_NOT_CONFIGURED = "E_BLINK_NOT_CONFIGURED"
E_BLINK_PAYMENT_FAILED = "E_BLINK_PAYMENT_FAILED"
E_BLINK_INVALID_ADDRESS = "E_BLINK_INVALID_ADDRESS"
E_BLINK_AMOUNT_OUT_OF_RANGE = "E_BLINK_AMOUNT_OUT_OF_RANGE"

# ── Survey ───────────────────────────────────────────────────────────────────
E_SURVEY_NOT_FOUND = "E_SURVEY_NOT_FOUND"
E_SURVEY_CLOSED = "E_SURVEY_CLOSED"
E_SURVEY_INVALID_ANSWER = "E_SURVEY_INVALID_ANSWER"

# ── Harvest (오렌지 수확 회차) ────────────────────────────────────────────────
E_HARVEST_ROUND_NOT_FOUND = "E_HARVEST_ROUND_NOT_FOUND"
E_HARVEST_INVALID_RANGE = "E_HARVEST_INVALID_RANGE"
E_HARVEST_ROUND_OVERLAP = "E_HARVEST_ROUND_OVERLAP"
E_HARVEST_ALREADY_PAID = "E_HARVEST_ALREADY_PAID"
E_HARVEST_INVALID_MONTH = "E_HARVEST_INVALID_MONTH"


def api_error(status_code: int, code: str, message: str) -> HTTPException:
    """Return an HTTPException whose detail carries both a machine-readable code
    and a human-readable Korean message."""
    return HTTPException(status_code=status_code, detail={"code": code, "message": message})
