"""remove_week_label_and_mining_rounds

Revision ID: 2ea26af9a1fe
Revises: a9b2c3d4e5f6
Create Date: 2026-05-30 16:15:19.680215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea26af9a1fe'
down_revision: Union[str, None] = 'a9b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mining_rounds')
    with op.batch_alter_table('challenge_participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_participations_user_challenge'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))

    with op.batch_alter_table('lightning_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lightning_claims_week_status'))
        batch_op.drop_column('week_label')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posts_share_token'), type_='unique')

    with op.batch_alter_table('reward_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_points_status_created'))
        batch_op.drop_index(batch_op.f('ix_reward_points_user_week_status'))
        batch_op.drop_column('week_label')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_label', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_reward_points_user_week_status'), ['user_id', 'week_label', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_points_status_created'), ['status', 'created_at'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_posts_share_token'), ['share_token'])

    with op.batch_alter_table('lightning_claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_label', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_lightning_claims_week_status'), ['week_label', 'status'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('challenge_participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_participations_user_challenge'), ['user_id', 'challenge_id'], unique=False)

    op.create_table('mining_rounds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('week_label', sa.VARCHAR(), nullable=False),
    sa.Column('total_pool_sats', sa.INTEGER(), nullable=False),
    sa.Column('sats_per_block', sa.INTEGER(), nullable=False),
    sa.Column('total_blocks', sa.INTEGER(), nullable=False),
    sa.Column('participant_count', sa.INTEGER(), nullable=False),
    sa.Column('winner_count', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('result_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('distributed_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_label')
    )
    # ### end Alembic commands ###
