"""add_original_video_audio_r2_key_to_videos

Revision ID: 373761a37e3f
Revises: 9b7c6d5e4f31
Create Date: 2026-06-20 10:52:03.635070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373761a37e3f'
down_revision: Union[str, None] = '9b7c6d5e4f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_video_r2_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('original_audio_r2_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('original_audio_r2_key')
        batch_op.drop_column('original_video_r2_key')

    # ### end Alembic commands ###
