"""add_mining_rounds

Revision ID: a2ab4099d3f3
Revises: c1d2e3f4a5b6
Create Date: 2026-05-26 13:52:48.624080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ab4099d3f3'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_label', sa.String(), nullable=False),
    sa.Column('total_pool_sats', sa.Integer(), nullable=False),
    sa.Column('sats_per_block', sa.Integer(), nullable=False),
    sa.Column('total_blocks', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mining_rounds')
    # ### end Alembic commands ###
