"""add harvest rounds and allocations

Revision ID: e5fd7b9b4af7
Revises: 2585a9906a8e
Create Date: 2026-09-29 09:55:15.199492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fd7b9b4af7'
down_revision: Union[str, None] = '2585a9906a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_oranges', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploads', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('oranges', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['harvest_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'user_id', name='uq_harvest_allocation_round_user')
    )
    with op.batch_alter_table('harvest_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_allocations_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_harvest_allocations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_allocations_user_id'))
        batch_op.drop_index(batch_op.f('ix_harvest_allocations_round_id'))

    op.drop_table('harvest_allocations')
    op.drop_table('harvest_rounds')
    # ### end Alembic commands ###
